[tool.poetry]
name = "Simplex"
version = "0.1.0"
description = ""
authors = ["iTrooz"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
sympy = "^1.12"
colorama = "^0.4.6"
tabulate = "^0.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
